name: build-macosx-arm64

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Git repository to clone'
        required: true
        default: 'https://bitbucket.org/bkhtmltopdf/java-cef.git'
      ref:
        description: 'Git commit id to checkout'
        required: true
        default: 'response-filter'

jobs:
  build-macosx-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Setup environment
        run: |
          chmod +x scripts/install_macos_dependencies.sh
          ./scripts/install_macos_dependencies.sh
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'
      -
        name: Build
        run: |
          chmod +x compile_macosx.sh
          ./compile_macosx.sh arm64 Release ${{ github.event.inputs.repo }} ${{ github.event.inputs.ref }}
      -
        name: Export artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macosx-arm64.tar.gz
          path: out/binary_distrib.tar.gz

